<?php

return [
    'anteraja' => [
        'priority' => 0,
        'code' => 'anteraja',
        'response_code' => 'anteraja',
        'label' => 'AnterAja',
        'website' => 'http://anteraja.id',
        'services_domestic' => ['ND' => 'Next Day', 'REG' => 'Regular', 'SD' => 'Same Day'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'dse' => [
        'priority' => 0,
        'code' => 'dse',
        'response_code' => 'dse',
        'label' => '21 Express',
        'website' => 'http://21express.co.id',
        'services_domestic' => ['ECO' => 'Regular Service', 'ONS' => 'Over Night Service', 'SDS' => 'Same Day Service'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'expedito' => [
        'priority' => 0,
        'code' => 'expedito',
        'response_code' => 'expedito',
        'label' => 'Expedito',
        'website' => 'http://www.expedito.co.id',
        'services_domestic' => [],
        'services_international' => ['ARAMEX Indonesia' => 'ARAMEX Indonesia', 'CityLink Express' => 'CityLink Express', 'CityLink' => 'CityLink', 'DHL  JKT' => 'DHL JKT', 'DHL Singapore' => 'DHL Singapore', 'DPEX' => 'DPEX', 'Moon Forwarder' => 'Moon Forwarder', 'NetworkCourierSG' => 'NetworkCourierSG', 'SF EXPRESS' => 'SF EXPRESS', 'SkyNet Worldwide' => 'SkyNet Worldwide', 'SkySaver by Skynet Worldwide' => 'SkySaver by Skynet Worldwide', 'TNT | Fedex' => 'TNT | Fedex'],
        'account_domestic' => [],
        'account_international' => ['starter', 'basic', 'pro'],
    ],
    'ide' => [
        'priority' => 0,
        'code' => 'ide',
        'response_code' => 'ide',
        'label' => 'IDExpress',
        'website' => 'http://idexpress.com',
        'services_domestic' => ['STD' => 'Reguler', 'Idtruck' => 'Cargo', 'IDlite' => 'Lite'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'jne' => [
        'priority' => 0,
        'code' => 'jne',
        'response_code' => 'jne',
        'label' => 'JNE',
        'website' => 'http://www.jne.co.id',
        'services_domestic' => ['CTC' => 'City Courier', 'CTCYES' => 'City Courier YES', 'CTCSPS' => 'City Courier SPS', 'OKE' => 'Ongkos Kirim Ekonomis', 'REG' => 'Layanan Reguler', 'YES' => 'Yakin Esok Sampai', 'JTR<130' => 'Cargo', 'JTR>130' => 'Cargo', 'JTR>200' => 'Cargo', 'JTR>2000' => 'Cargo'],
        'services_international' => ['INTL Service' => 'Paket'],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => ['starter', 'basic', 'pro'],
    ],
    'jnt' => [
        'priority' => 0,
        'code' => 'jnt',
        'response_code' => 'J&T',
        'label' => 'J&T Express',
        'website' => 'http://www.jet.co.id',
        'services_domestic' => ['EZ' => 'Regular Service'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'lion' => [
        'priority' => 0,
        'code' => 'lion',
        'response_code' => 'lion',
        'label' => 'Lion Parcel',
        'website' => 'http://lionparcel.com',
        'services_domestic' => ['JAGOPACK' => 'Economy Service', 'REGPACK' => 'Regular Service', 'BOSSPACK' => 'Boss Service', 'BIGPACK' => 'Big Package Service', 'LANDPACK' => 'Logistic Service', 'ONEPACK' => 'One Day Service', 'OTOPACK150' => 'Oto Service', 'OTOPACK250' => 'Oto Service'],
        'services_international' => ['INTERPACK' => 'INTERPACK'],
        'account_domestic' => ['pro'],
        'account_international' => ['starter', 'basic', 'pro'],
    ],
    'ncs' => [
        'priority' => 0,
        'code' => 'ncs',
        'response_code' => 'ncs',
        'label' => 'Nusantara Card Semesta',
        'website' => 'http://www.ptncs.com',
        'services_domestic' => ['DARAT' => 'Regular Darat', 'NRS' => 'REGULAR SERVICE', 'ONS' => 'One Night Service', 'JMR' => 'Jawa Murah', 'NFR' => 'Food-Regular Service', 'NFO' => 'Food-One Night Service'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'ninja' => [
        'priority' => 0,
        'code' => 'ninja',
        'response_code' => 'ninja',
        'label' => 'Ninja Xpress',
        'website' => 'https://www.ninjaxpress.co',
        'services_domestic' => ['STANDARD' => 'Standard Service'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'pos' => [
        'priority' => 0,
        'code' => 'pos',
        'response_code' => 'pos',
        'label' => 'POS Indonesia',
        'website' => 'http://www.posindonesia.co.id',
        'services_domestic' => ['Pos Reguler' => 'Reguler', 'Pos Nextday' => 'Nextday', 'PAKETPOS DANGEROUS GOODS' => 'PAKETPOS DANGEROUS GOODS', 'PAKETPOS VALUABLE GOODS' => 'PAKETPOS VALUABLE GOODS', 'Pos Sameday' => 'Sameday', 'POS KARGO' => 'POS KARGO'],
        'services_international' => ['PAKETPOS BIASA LN' => 'PAKETPOS BIASA LN', 'EMS BARANG' => 'EMS BARANG', 'ePacket LP APP' => 'ePacket LP APP', 'POS EKSPOR' => 'POS EKSPOR', 'PAKETPOS CEPAT LN' => 'PAKETPOS CEPAT LN', 'R LN' => 'R LN'],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => ['starter', 'basic', 'pro'],
    ],
    'ray' => [
        'priority' => 0,
        'code' => 'ray',
        'response_code' => 'ray',
        'label' => 'RAY',
        'website' => 'https://rayspeed.com/',
        'services_domestic' => [],
        'services_international' => ['Reguler Service' => 'Reguler Service', 'Express Service' => 'Express Service'],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'rex' => [
        'priority' => 0,
        'code' => 'rex',
        'response_code' => 'rex',
        'label' => 'Royal Express Indonesia',
        'website' => 'https://www.rex.co.id',
        'services_domestic' => ['EXP' => 'EXPRESS', 'REG' => 'REGULAR', 'REX-1' => 'REX-1', 'REX-10' => 'REX-10', 'REX-5' => 'REX-5'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'rpx' => [
        'priority' => 0,
        'code' => 'rpx',
        'response_code' => 'rpx',
        'label' => 'RPX',
        'website' => 'http://www.rpx.co.id',
        'services_domestic' => ['Regular Package (RGP)' => 'Regular Package', 'Next Day Package (NDP)' => 'Next Day Package', 'SameDay Package (SDP)' => 'SameDay Package', 'MidDay Package (MDP)' => 'MidDay Package', 'Economy Delivery (ECP)' => 'Economy Delivery', 'Heavy Weight Delivery (HWP)' => 'Heavy Weight Delivery'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'sap' => [
        'priority' => 0,
        'code' => 'sap',
        'response_code' => 'sap',
        'label' => 'SAP Express',
        'website' => 'http://sap-express.id',
        'services_domestic' => ['UDRREG' => 'Reguler', 'UDRONS' => 'Ons', 'DRGREG' => 'Cargo'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'sentral' => [
        'priority' => 0,
        'code' => 'sentral',
        'response_code' => 'sentral',
        'label' => 'Sentral Cargo',
        'website' => 'http://sentralcargo.co.id',
        'services_domestic' => ['DARAT ELEKTRONIK' => 'DARAT ELEKTRONIK', 'DARAT NON ELEKTRONIK' => 'DARAT NON ELEKTRONIK', 'UDARA ELEKTRONIK' => 'UDARA ELEKTRONIK', 'UDARA NON ELEKTRONIK' => 'UDARA NON ELEKTRONIK'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'sicepat' => [
        'priority' => 0,
        'code' => 'sicepat',
        'response_code' => 'sicepat',
        'label' => 'SiCepat Express',
        'website' => 'http://www.sicepat.com',
        'services_domestic' => ['REG' => 'Layanan Reguler', 'BEST' => 'Besok Sampai Tujuan', 'GOKIL' => 'Cargo', 'SIUNT' => 'SiUntung'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'star' => [
        'priority' => 0,
        'code' => 'star',
        'response_code' => 'star',
        'label' => 'Star Cargo',
        'website' => 'http://www.starcargo.co.id',
        'services_domestic' => ['Dokumen' => 'Dokumen', 'Express' => 'Express', 'MOTOR 150 - 250 CC' => 'MOTOR 150 - 250 CC', 'MOTOR' => 'MOTOR', 'Parcel' => 'Parcel', 'Reguler' => 'Reguler'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'tiki' => [
        'priority' => 0,
        'code' => 'tiki',
        'response_code' => 'tiki',
        'label' => 'TIKI',
        'website' => 'http://tiki.id',
        'services_domestic' => ['ECO' => 'Economy Service', 'HDS' => 'Holiday Services', 'ONS' => 'Over Night Service', 'REG' => 'Regular Service', 'SDS' => 'Same Day Service', 'TRC' => 'Trucking Service'],
        'services_international' => ['WDX' => 'World Document Express', 'WPX' => 'World Post Express'],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
    'wahana' => [
        'priority' => 0,
        'code' => 'wahana',
        'response_code' => 'wahana',
        'label' => 'Wahana Express',
        'website' => 'http://www.wahana.com',
        'services_domestic' => ['Normal' => 'Normal Service'],
        'services_international' => [],
        'account_domestic' => ['starter', 'basic', 'pro'],
        'account_international' => [],
    ],
];
